retail_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres         # 👈 use service name (from docker-compose)
      user: airflow
      password: airflow
      dbname: retail_db
      schema: data_etl      # 👈 schema where models will be built
      port: 5432
      threads: 1
